### ISSUE TITLE
no gulpfile found

### ISSUE THREAD

**Issue by njzjz** [quniu/ssmgr-deploy#1]
```
> shadowsocks-manager@0.27.8 prepare /usr/local/shadowsocks-manager
> gulp

[16:42:32] No gulpfile found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shadowsocks-manager@0.27.8 prepare: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shadowsocks-manager@0.27.8 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                       ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-25T08_42_32_421Z-debug.log
[Error] shadowsocks-manager install failed!
```

**Comment by quniu** [comment]
> ```
> > shadowsocks-manager@0.27.8 prepare /usr/local/shadowsocks-manager
> > gulp
> 
> [16:42:32] No gulpfile found
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! shadowsocks-manager@0.27.8 prepare: `gulp`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the shadowsocks-manager@0.27.8 prepare script.
> npm ERR! This is probably not a problem with npm. There is likely additional log                                                                       ging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-01-25T08_42_32_421Z-debug.log
> [Error] shadowsocks-manager install failed!
> ```

npm install gulp -g
